#////////////RPEXT CONFIG//////////////#
DebugMode: false
UseGoldNuggetBank: true
UseThirst: true
UseSleep: true
#//////EXPERIMENTAL!!!/////////////////#
UseChairs: false 

#SETTINGS

MoneyID: 371
MoneyUnit: 'g'
MoneyName: '§cCoin'
ChairID: 53
#//////////////END CONFIG///////////////#