#////////////RPEXT CONFIG//////////////#
DebugMode: false
UseGoldNuggetBank: true
UseThirst: true
UseSleep: true
#//////EXPERIMENTAL!!!/////////////////#
UseChairs: false 

#SETTINGS

ChairID: 53
#//////////////END CONFIG///////////////#