name: 'RP-Extensions'
main: 'com.jcamtech.rpextensions.MainClass'
version: '0.0.12'
api-version: '1.20'
softdepend: [Vault, Essentials]
commands:
    stats:
        description: Displays your stats
        useage: /stats
        permission: rpext.read
        permission-message: You don't have rpext.read in your permissions!
    checkstats:
        description: Displays others stats
        useage: /checkstats [player]
        permission: rpext.checkstats
        permission-message: You don't have rpext.checkstats in your permissions!
    gstore:
        description: Stores your gold
        useage: /gstore [amount]
        permission: rpext.gstore
        permission-message: You don't have rpext.gstore in your permissions!
    gtake:
        description: Takes your gold
        useage: /gtake [amount]
        permission: rpext.gtake
        permission-message: You don't have rpext.gtake in your permissions!
    gtransfer:
        description: Transfers gold to another player
        useage: /gtransfer [player] [amount]
        permission: rpext.gtransfer
        permission-message: You don't have rpext.gtransfer in your permissions!
    gset:
        description: Transfers gold to another player
        useage: /gset [player] [amount]
        permission: rpext.gset
        permission-message: You don't have rpext.gset in your permissions!
    quench:
        description: Quenches Thirst
        useage: /quench
        permission: rpext.quench
        permission-message: You don't have rpext.quench in your permissions!
    sleep:
        description: resets sleepiness
        useage: /sleep
        permission: rpext.sleep
        permission-message: You don't have rpext.sleep in your permissions!
    convertEcon:
        description: Converts economy to vault
        useage: /convertEcon
        permission: rpext.convertEcon
        permission-message: You don't have rpext.convertEcon in your permissions!
permissions:
    rpext.*:
        description: Gives access to all rpext commands
        children:
            rpext.read: true
            rpext.checkstats: true
            rpext.gstore: true
            rpext.gtake: true
            rpext.gtransfer: true
            rpext.quench: true
            rpext.createatm: true
            rpext.sleep: true
            rpext.gset: true
            rpext.ggive: true
            rpext.convertEcon: true
    rpext.read:
        description: Allows you to read stats
        default: true
    rpext.checkstats:
        description: Allows you to check others stats
        default: false
    rpext.gstore:
        description: Allows you to store gold
        default: false
    rpext.gtake:
        description: Allows you to take stored gold
        default: false
    rpext.gtransfer:
        description: Allows you to transfer gold to another player
        default: false
    rpext.ggive:
        description: Allows you to give gold to another player
        default: false
    rpext.gset:
        description: Allows you to set the gold in another players account
        default: false
    rpext.quench:
        description: Allows you to quench your own thirst
        default: false
    rpext.quench.others:
        description: Allows you to quench the thirst of others
        default: false
    rpext.createatm:
        description: Allows you to make an ATM machine
        default: false
    rpext.sleep:
        description: Allows player to reset sleep variable
        default: false
    rpext.sleep.others:
        description: Allows you to reset the sleep variable of others
        default: false
    rpext.convertEcon:
        description: Allows player to convert the economy to vault
        default: false